---
name: Test Server Build/Deploy
run-name: Test Server deployment by ${{ gitea.actor }}
concurrency: staging
on:
  push:
    branches:
      - main

# based on https://github.com/actions/upload-pages-artifact/blob/main/action.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Install Jekyll
        run: |
          gem install jekyll bundler
      - name: Jekyll Compile
        run: |
          bundle
          bundle exec jekyll build
      - name: Debug ls
        run: |
          echo "Contents of `pwd`:"
          ls -al
          echo "Contents of $RUNNER_TEMP:"
          ls -al $RUNNER_TEMP
      - name: Archive artifact
        shell: sh
        run: |
          tar \
            --dereference --hard-dereference \
            --directory "./_site" \
            -cvf "$RUNNER_TEMP/artifact.tar" \
            --exclude=.git \
            --exclude=.github \
            --exclude=.gitea \
            --transform "s#^\_site/#pages-archive/#" \
            .
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: pages-archive.tar
          path: ${{ runner.temp }}/artifact.tar
          retention-days: 1
          if-no-files-found: error
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    needs: build
    steps:
      #- name: Install rsync (WHYYY)
      #  run: apt install -y rsync
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host $SSH_HOST
            Hostname     $SSH_HOST
            User         $SSH_USER
            IdentityFile ~/.ssh/staging.key
          END
          echo "$SSH_HKEY" >> ~/.ssh/known_hosts
          cat ~/.ssh/config
        env:
          SSH_USER: ${{ secrets.STAGING_SSH_USER }}
          SSH_KEY:  ${{ secrets.STAGING_SSH_KEY }}
          SSH_HOST: ${{ secrets.STAGING_SSH_HOST }}
          SSH_HKEY: ${{ secrets.STAGING_SSH_HOSTKEY }}
      #- name: Debug OS
      #  run: cat /etc/os-release
      - name: Download website
        uses: actions/download-artifact@v3
        with:
          name: pages-archive.tar
      - name: Debug ls
        run: |
          echo "Contents of `pwd`:"
          ls -alR
          echo "Contents of $RUNNER_TEMP:"
          ls -al $RUNNER_TEMP
      - name: Extract website
        run: tar -xvf pages-archive.tar/artifact.tar
      - name: Deploy to server via rsync
        run: |
          echo Deploying ${STAGING_SSH_USER}@${STAGING_SSH_HOST}:${STAGING_WEB_FILEPATH}
          rsync -avz --delete --exclude=settings.js pages-archive/ ${STAGING_SSH_HOST}:${STAGING_WEB_FILEPATH}
        env:
          STAGING_SSH_USER: ${{ secrets.STAGING_SSH_USER }}
          STAGING_SSH_HOST: ${{ secrets.STAGING_SSH_HOST }}
          STAGING_WEB_FILEPATH: ${{ secrets.STAGING_WEB_FILEPATH }}
      #- name: eepy debug
      #  run: sleep 300

