---
name: Test Server Build/Deploy
run-name: Test Server deployment by ${{ gitea.actor }}
on:
  push:
    branches:
      - main

# based on https://github.com/actions/upload-pages-artifact/blob/main/action.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Jekyll Compile
        uses: actions/jekyll-build-pages@v1
      - name: Archive artifact
        shell: sh
        run: |
          tar \
            --dereference --hard-dereference \
            --directory "./_site/" \
            -cvf "$RUNNER_TEMP/artifact.tar" \
            --exclude=.git \
            --exclude=.github \
            .
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: pages-archive
          path: ${{ runner.temp }}/artifact.tar
          retention-days: 1
          if-no-files-found: error